weight/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app_test.views.home', name='home'),
    # url(r'^app_test/', include('app_test.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('frontend.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

core/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from core.choices import DISH_TYPES

# Create your models here.

class PortalUser(User):
    recommended = models.ManyToManyField('Recipe', related_name='recommending_users')
    recently_viewed = models.ManyToManyField('Recipe', related_name='recent_viewers')
    followers = models.ManyToManyField('self', related_name='following')
    height = models.CharField(max_length=50, null=True)
    birth_date = models.CharField(max_length=50, null=True)


class Recipe(models.Model):
    title = models.CharField(max_length=255, null=False)
    substracts = models.TextField()
    content = models.TextField()
    author = models.ForeignKey(PortalUser)


class Diet(models.Model):
    user = models.ForeignKey(PortalUser)
    start_weight = models.CharField(max_length=50, null=False)
    date_start = models.DateField(auto_now_add=True)


class DailyCheckup(models.Model):
    diet = models.ForeignKey(Diet, related_name='checkups')
    weight = models.CharField(max_length=50, null=True)
    date = models.DateField(default=datetime.date.today)
    bmi = models.CharField(null=True, max_length=20)


class Dish(models.Model):
    type = models.IntegerField(null=False, choices=DISH_TYPES.items())
    title = models.CharField(max_length=255, null=True)
    date_of_consumption = models.DateField(default=datetime.date.today)
    hour_of_consumption = models.CharField(max_length=20)
    calories = models.CharField(max_length=10, null=True)
    description = models.TextField(null=True)
#    diet = models.ForeignKey(Diet)
    checkup = models.ForeignKey(DailyCheckup, related_name='dishes')

    class Meta:
        ordering = ['type']

templates/backend/article_edit.html
{% extends 'backend/base.html' %}
{% load core_tags %}
{% block extrahead %}
	{% if form.initial.article_id %}
		<script type="text/javascript">
			// $(document).ready(function() {
			     // $('.inline-edit').editable('{% url backend-partial-edit-view form.initial.article_id %}', { 
			         // type      : 'textarea',
			         // cancel    : 'Cancel',
			         // submit    : 'OK',
			         // indicator : 'Saving...',
			         // method	   : 'POST',
			         // tooltip   : 'Click to edit...',
			         // callback  : function(value, settings){
			         	// console.log(jQuery.parseJSON(value))
			         // }
			     // });
			 // });
			 $(document).ready(function() {
			 	$(".inline-edit").editInPlace({
					url: "{% url backend-partial-edit-view article_id=form.initial.article_id %}",
					bg_over: "#cff",
					field_type: "textarea",
					textarea_rows: "15",
					textarea_cols: "35",
					saving_image: "./images/ajax-loader.gif",
					success: function(response){
						console.log($('#id_content'))
						$('#id_content').val(response)
					},
					show_buttons: "true",
					cancel_button: "<button class='btn inplace_cancel'>Anuluj</button>",
					save_button: "<button class='btn inplace_save'>Ok</button>"
				}); 
				
			 });
		</script>
	{% endif %}
{% endblock %}
{% block content %}
<form action="" method="post">
	{% csrf_token %}
	{{form.title.label_tag}}
	{{form.title}}
	{{form.title.errors}}
	{% if form.initial.content %}
		<div class="inline-edit" id="content">
			{{form.initial.content|linebreaks|safe}}
		</div>
		{{form.content}}
	{% else %}
		{{form.content.label_tag}}
		{{form.content}}
		{{form.content.errors}}
	{% endif %}
	{{form.article_id}}
	{{ video_formset.management_form }}
	<div class="video_formset">
		{% for video_form in video_formset %}
			<div class="video">
				{{video_form}}
				{% if video_form.initial.url %}
					<a href="{% url backend-delete-video-view video_form.initial.video_id %}" title="Usuń" class="delete"><span>Usuń</span></a>
					{{video_form.initial.url|embed:"220x165"|safe}}
				{% endif %}
			</div>
		{% endfor %}
	</div>
	<div>
		<button class="btn">Zapisz</button>
	</div>
</form>
{% endblock %}

templates/backend/article_list.html
{% extends 'backend/base.html' %}
{% block content %}
	<div>
		<a href="{% url backend-add-view %}" class="btn btn-primary">Dodaj nowy artykuł</a>
	</div>
	<table>
		<thead>
			<tr>
				<th class="id">
					Id
				</th>
				<th class="title">
					Tytuł
				</th>
				<th class="date-published">
					Data publikacji
				</th>
				<th class="actions">
					Akcje
				</th>
			</tr>
		</thead>
		<tbody>
		{% for article in articles %}
			<tr>
				<td>
					{{article.id}}
				</td>
				<td>
					{{article.title}}
				</td>
				<td>
					{{article.add_date}}
				</td>
				<td>
					<a href="{% url backend-edit-view article.id %}">Edytuj</a>
					<a href="">Usuń</a>
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/backend/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Backend</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/backend.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/static/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/ico/apple-touch-icon-57-precomposed.png">
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    <!-- <script src="/static/js/jEditable.js"></script> -->
    <script src="/static/js/jquery.editinplace.js"></script>
    {% block extrahead %}
    {% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{% url backend-main-view %}">Test</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="{% url backend-list-view %}">Artykuły</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
		{% block content %}
		{% endblock %}
    </div> <!-- /container -->
  </body>
</html>

templates/backend/main.html
{% extends 'backend/base.html' %}
{% block content %}
{% endblock %}